server:
  # 服务端口号
  port: 30001
  servlet:
    context-path: /sms
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: sms-service
  datasource:
      url: jdbc:mysql://localhost:3306/lhy?useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: xykj
  redis:
    #Redis数据库索引（默认为0）
      database: 0
      host: localhost
      port: 6379
      password:
      #连接超时时间（毫秒）
      timeout: 10000ms
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait:
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 0

eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://127.0.0.1:10081/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# ribbon客户端负载均衡，默认的负载均衡策略是轮询
ribbon:
  #建立连接超时时间
  ConnectTimeout: 5000
  #读取资源超时间
  ReadTimeout: 5000

# 忽略hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

rocketmq:
  consumer:
    groupName: SmsMQPushConsumer
    namesrvAddr: 127.0.0.1:9876
    topic: sms