server:
  # 服务端口号
  port: 10089
  servlet:
    context-path: /book
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: book-service
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://127.0.0.1:10081/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# Elasticsearch配置
elasticsearch:
  host: 127.0.0.1
  port: 9200
  #配置es的集群名称，默认是elasticsearch
  cluser:
    name: elasticsearch

rocketmq:
  consumer:
    groupName: TestRocketMQPushConsumer
    namesrvAddr: 127.0.0.1:9876
