server:
  servlet:
    context-path: /user
spring:
  profiles:
    active: one
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: user-service
  cloud:
    config:
      # 配置文件环境
      profile: dev
      discovery:
        # 开启配置中心
        enabled: true
        # 配置中心别名
        service-id: service-config
  datasource:
    #url: jdbc:mysql://localhost:3306/lhy?useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://192.168.1.153:3306/users?useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: xykj
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    host: 192.168.1.153
    port: 6379
    password:
    #连接超时时间（毫秒）
    timeout: 10000ms
    #连接池最大连接数（使用负值表示没有限制）
    max-active: 8
    #连接池最大阻塞等待时间（使用负值表示没有限制）
    max-wait:
    #连接池中的最大空闲连接
    max-idle: 8
    #连接池中的最小空闲连接
    min-idle: 0
  jpa:
    #日志中打印出执行的 SQL 语句信息
    show-sql: true
    #将默认的存储引擎切换为 InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none


# pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 是否开启超时熔断, 如果为false, 则熔断机制只在服务不可用时开启
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true