server:
  # 服务端口号
  port: 10083
  servlet:
    context-path: /task
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: task-service
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://127.0.0.1:10081/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# ribbon客户端负载均衡，默认的负载均衡策略是轮询
ribbon:
  #建立连接超时时间
  ConnectTimeout: 5000
  #读取资源超时间
  ReadTimeout: 5000


#服务降级
feign:
  hystrix:
    enabled: true

rocketmq:
  consumer:
    groupName: TestRocketMQPushConsumer
    namesrvAddr: 127.0.0.1:9876
    topic: vip


