server:
  #服务端口号
  port: 10100
spring:
  application:
    #服务名称 - 服务之间使用名称进行通讯
    name: service-gateway
  redis:
      #Redis数据库索引（默认为0）
      database: 0
      host: 192.168.1.153
      port: 6379
      password:
      #连接超时时间（毫秒）
      timeout: 10000ms
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait:
      #连接池中的最大空闲连接
      max-idle: 8
      #连接池中的最小空闲连接
      min-idle: 0
  cloud:
      gateway:
        routes:
          #认证服务路由
          - id: user-service
            predicates:
              - Path=/user/**
            # 匹配成功，转发给对应的uri
            uri: lb://user-service
            filters:
#              # 设置prefix参数来路径前缀
#              - PrefixPath=/mypath
#               #截断路径前缀的数量
#              - StripPrefix=1
          - id: task-service
            predicates:
                - Path=/task/**
            uri: lb://task-service
eureka:
  client:
    service-url:
      #填写注册中心服务器地址
      defaultZone: http://localhost:10081/eureka
